CREATE TABLE banco (
codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
numero BIGINT(20) NOT NULL,
nome VARCHAR (50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE proposta (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	ade VARCHAR(50) NOT NULL,
	descricao TEXT NOT NULL,
	valor_parcela DECIMAL (10,2) NOT NULL,
	valor_total  DECIMAL (10,2) NOT NULL,
	valor_liquido  DECIMAL (10,2) NOT NULL,
	comissao DECIMAL (10,2) NOT NULL,
	codigo_banco BIGINT(20) NOT NULL,
	FOREIGN KEY (codigo_banco) REFERENCES banco(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	
	INSERT INTO banco VALUES (0, 0, 'ITAU');
	INSERT INTO banco VALUES (0, 0, 'SANTANDER');