CREATE TABLE equipe (
codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT UNIQUE,
nome VARCHAR (50) NOT NULL UNIQUE,
bonus DECIMAL (10,2) NOT NULL,
codigo_usuario BIGINT(20) NOT NULL ,
FOREIGN KEY (codigo_usuario) REFERENCES usuario(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
