CREATE TABLE cliente (
codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT UNIQUE,
nome VARCHAR (50) NOT NULL,
sobrenome VARCHAR (50) NOT NULL,
cpf VARCHAR (50) NOT NULL UNIQUE,
rg VARCHAR (50) NOT NULL UNIQUE,
email VARCHAR (50) NOT NULL UNIQUE,
telefone VARCHAR (50) NOT NULL,
genero VARCHAR(50) NOT NULL,
codigo_conta BIGINT(20) ,
FOREIGN KEY (codigo_conta) REFERENCES conta(codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;